version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./data/registry:/var/lib/registry:rw
      - ./conf/registry/simple.yml:/etc/docker/registry/config.yml:ro

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry