version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - ./data/registry:/var/lib/registry:rw
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=My Private Docker Registry
    volumes:
      - ./conf/ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/ui/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./conf/ui/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net: