services:
  registry-ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      # For deleting images, you need to activate the delete feature in the UI with DELETE_IMAGES=true and in your registry.
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    networks:
      - traefik-net 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registryui.rule=Host(`myregistry.com`)"
        - "traefik.http.routers.registryui.entrypoints=web"
        - "traefik.http.services.registryui.loadbalancer.server.port=80"
        - "traefik.http.routers.registryui.service=registryui"
  registry:
    image: registry:2.8.3
    volumes:
      - ./images:/var/lib/registry
      - ./htpasswd:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth
      - REGISTRY_HTTP_RELATIVEURLS=true
      # For deleting images, you need to activate the delete feature in the registry.
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true