name: Run tests on PRs and branches

on:
  pull_request:
  push:
    branches-ignore: [ main, master, netskope@main ]

jobs:
  build:
    runs-on: [ self-hosted, linux, x64, cheap, sz-L ]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build the interface
      run: npm run build
      env:
        DEVELOPMENT_BUILD: ${{ github.event.pull_request.head.sha }}
