apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  labels:
    app: registry-ui
    release: docker-registry-ui
    app/version: "1.2.1"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: registry-ui
      release: docker-registry-ui

