version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry.yml:/etc/docker/registry/config.yml
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - SINGLE_REGISTRY=true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./write.htpasswd:/etc/nginx/auth/write.htpasswd:ro
      - ./read.htpasswd:/etc/nginx/auth/read.htpasswd:ro
    depends_on:
      - registry
    networks:
      - registry-ui-net
networks:
  registry-ui-net:
