version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - ./data/registry:/var/lib/registry:rw
      - ./conf/registry/config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - SINGLE_REGISTRY=true
    volumes:
      - ./conf/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/proxy/read-write.htpasswd:/etc/nginx/auth/read-write.htpasswd:ro
      - ./conf/proxy/read-only.htpasswd:/etc/nginx/auth/read-only.htpasswd:ro
    depends_on:
      - registry
    networks:
      - registry-ui-net
networks:
  registry-ui-net: